### ISSUE TITLE
How can i increase the font size of track numbering value?   

### ISSUE THREAD

**Issue by iPatilAmit** [rameezhandel/SmartGauge#1]
Hi @rameezhandel 
I have implemented this library in code and its fit with all my requirement. We are going happy to use this library.
can you please tell me how can I increase the numbers font size?

Thank you

**Comment by rameezhandel** [comment]
@iPatilAmit 
The font size is calculated dynamically based on the "RADIUS" of the Gauge. 
If it is necessary we can provide an option to set the fixed font size in future release.

**Comment by iPatilAmit** [comment]
@rameezhandel 

Thanks for the reply 

Yes, It's necessary for me can u please help me out with it. I have used SmartGauge view at the bottom of my view with a required size but I want to increase the font size of that number? 
Let me know how can I do that.

Thank You

**Comment by rameezhandel** [comment]
@iPatilAmit 
Fixed in latest version (0.6.3)

`gaugeView. tickValueFontSize = 20.0 `
